# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-24 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
