# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-25 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0002_auto_20170624_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='logo',
            field=models.URLField(),
        ),
    ]
