# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0008_auto_20170527_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('president', 'president'), ('member', 'member')], default=datetime.datetime(2017, 6, 22, 9, 24, 3, 75702, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
